[project]
name = "gopro360"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gpmf>=0.1",
    "numpy>=2.5.1",
    "onnxruntime>=1.28.0",
    "onnxscript>=0.7.1",
    "opencv-python>=5.0.0.93",
    "py-gpmf-parser>=0.1.1",
    "raft>=1.6",
    "scipy>=1.18.0",
    "torch>=2.13.0",
]

[project.scripts]
gopro360 = "gopro360:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
